const QUICK_ANIMATION_DELAY = 0.361;
const MEDIUM_ANIMATION_DELAY = 0.691;
const LARGE_ANIMATION_DELAY = 1.361;
const CUSTOM_EASING_1 = "cubic-bezier(.27,.12,.29,.9)";
const SECS_PER_QUESTION = 15;

const config = {
	QUICK_ANIMATION_DELAY,
	MEDIUM_ANIMATION_DELAY,
	LARGE_ANIMATION_DELAY,
	CUSTOM_EASING_1,
	SECS_PER_QUESTION,
};

export default config;
